import './globals.css'
import { Poppins } from 'next/font/google'
import MainNavigation from '@/components/MainNavigation';
import Footer from '@/components/Footer';

const poppins = Poppins({ 
  weight: ['400','600','700','800'],
  subsets: ['latin'],
  display: 'swap'
});

export const metadata = {
  title: 'Fremont Sign Company',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <MainNavigation/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
